# (HTTP and SOCKS5 in one port)
mixed-port: 7890
# RESTful API for clash
external-controller: :9090
mode: rule

proxies:
  - type: ss
    name: hk-01
    server: "iibrb-g05.hk01-ae5.entry.v50307shvkaa.art"
    port: 19275
    cipher: "aes-256-gcm"
    password: "1e54da11-43b1-3f5f-99fd-c255b22b3442"
    udp: true # 可选，是否启用 UDP 转发
  - type: ss
    name: hk-02
    server: "opoxw-g05.hk02-ae5.entry.v50307shvkaa.art"
    port: 14563
    cipher: "aes-256-gcm"
    password: "1e54da11-43b1-3f5f-99fd-c255b22b3442"
    udp: true # 可选，是否启用 UDP 转发
  - type: ss
    name: hk-04
    server: "iibrb-g05.hk01-ae5.entry.v50307shvkaa.art"
    port: 807
    cipher: "aes-256-gcm"
    password: "1e54da11-43b1-3f5f-99fd-c255b22b3442"
    udp: true # 可选，是否启用 UDP 转发
  - type: ss
    name: us-01
    server: "8f4c8-g05.us01-ae5.entry.v50307shvkaa.art"
    port: 20013
    cipher: "aes-256-gcm"
    password: "1e54da11-43b1-3f5f-99fd-c255b22b3442"
    udp: true # 可选，是否启用 UDP 转发

rules:
  - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,tld-not-cn,PROXY
  - RULE-SET,proxy,PROXY
  - RULE-SET,direct,DIRECT
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,gfw,PROXY
  - RULE-SET,tld-not-cn,PROXY
  - RULE-SET,telegramcidr,PROXY
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,PROXY
  - MATCH,DIRECT

proxy-groups:
  - name: "PROXY"
    type: select
    interval: 3000
    proxies:
      - "hk-01"
      - "hk-04"
      - "us-01"
      - "DIRECT"

rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  msh:
    type: file
    behavior: domain
    path: ./ruleset/msh.yaml

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  mshcidr:
    type: file
    behavior: ipcidr
    path: ./ruleset/mshcidr.yaml

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400
