---
apiVersion: v1
kind: Namespace
metadata:
  name: hbase
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: hbase
  labels:
    app: zookeeper
spec:
  ports:
    - port: 2181
      name: client
  selector:
    app: zookeeper
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: hbase
  labels:
    app: zookeeper
spec:
  serviceName: "zookeeper"
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: zookeeper:3.7
          ports:
            - containerPort: 2181
              name: client
          env:
            - name: ZOO_MY_ID
              value: "1"
            - name: ZOO_SERVERS
              value: server.1=zookeeper:2888:3888
          volumeMounts:
            - name: datadir
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: hbase-master
  namespace: hbase
  labels:
    app: hbase-master
spec:
  ports:
    - port: 16000
      name: master
    - port: 16010
      name: ui
  selector:
    app: hbase-master
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hbase-master
  namespace: hbase
  labels:
    app: hbase-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hbase-master
  template:
    metadata:
      labels:
        app: hbase-master
    spec:
      containers:
        - name: hbase-master
          image: harisekhon/hbase:latest
          ports:
            - containerPort: 16000
              name: master
            - containerPort: 16010
              name: ui
          env:
            - name: ZOOKEEPER_QUORUM
              value: "zookeeper.hbase.svc.cluster.local"
          volumeMounts:
            - name: hbase-config
              mountPath: /hbase/conf
      volumes:
        - name: hbase-config
          configMap:
            name: hbase-config
---
apiVersion: v1
kind: Service
metadata:
  name: hbase-regionserver
  namespace: hbase
  labels:
    app: hbase-regionserver
spec:
  ports:
    - port: 16020
      name: regionserver
    - port: 16030
      name: ui
  selector:
    app: hbase-regionserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hbase-regionserver
  namespace: hbase
  labels:
    app: hbase-regionserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hbase-regionserver
  template:
    metadata:
      labels:
        app: hbase-regionserver
    spec:
      containers:
        - name: hbase-regionserver
          image: harisekhon/hbase:latest
          ports:
            - containerPort: 16020
              name: regionserver
            - containerPort: 16030
              name: ui
          env:
            - name: ZOOKEEPER_QUORUM
              value: "zookeeper.hbase.svc.cluster.local"
          volumeMounts:
            - name: hbase-config
              mountPath: /hbase/conf
      volumes:
        - name: hbase-config
          configMap:
            name: hbase-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hbase-config
  namespace: hbase
data:
  hbase-site.xml: |
    <?xml version="1.0"?>
    <configuration>
      <property>
        <name>hbase.rootdir</name>
        <value>file:///hbase/data</value>
      </property>
      <property>
        <name>hbase.zookeeper.quorum</name>
        <value>zookeeper</value>
      </property>
      <property>
        <name>hbase.cluster.distributed</name>
        <value>true</value>
      </property>
      <property>
        <name>hbase.master.port</name>
        <value>16000</value>
      </property>
      <property>
        <name>hbase.regionserver.port</name>
        <value>16020</value>
      </property>
    </configuration>
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hbase-pvc
  namespace: hbase
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
