# clash-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: clash-service
  namespace: rss
spec:
  selector:
    app: clash
  ports:
    - name: proxy
      port: 7890
      targetPort: 7890
    - name: controller
      port: 9090
      targetPort: 9090
