# clash-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clash
  namespace: rss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clash
  template:
    metadata:
      labels:
        app: clash
    spec:
      containers:
        - name: clash
          image: dreamacro/clash-premium
          ports:
            - containerPort: 7890 # 代理端口
            - containerPort: 9090 # 控制端口
          volumeMounts:
            - name: config-volume
              mountPath: /root/.config/clash/config.yaml
              subPath: config.yaml
            - name: rules-volume
              mountPath: /ruleset
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
      volumes:
        - name: config-volume
          configMap:
            name: clash-config
        - name: ruleset-volume # 新增规则集卷
          configMap:
            name: clash-config
