# clash-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: clash-config
  namespace: rss
data:
  config.yaml: |
    mixed-port: 7890
    allow-lan: true
    external-controller: :9090
    mode: rule
    log-level: info

    proxies:
      - type: ss
        name: hk-01
        server: "iibrb-g05.hk01-ae5.entry.v50307shvkaa.art"
        port: 19275
        cipher: "aes-256-gcm"
        password: "1e54da11-43b1-3f5f-99fd-c255b22b3442"
        udp: true # 可选，是否启用 UDP 转发

    rules:
      - RULE-SET,applications,DIRECT
      - DOMAIN,clash.razord.top,DIRECT
      - DOMAIN,yacd.haishan.me,DIRECT
      - RULE-SET,private,DIRECT
      - RULE-SET,reject,REJECT
      - RULE-SET,tld-not-cn,PROXY
      - RULE-SET,proxy,PROXY
      - RULE-SET,direct,DIRECT
      - RULE-SET,icloud,DIRECT
      - RULE-SET,apple,DIRECT
      - RULE-SET,gfw,PROXY
      - RULE-SET,tld-not-cn,PROXY
      - RULE-SET,telegramcidr,PROXY
      - RULE-SET,lancidr,DIRECT
      - RULE-SET,cncidr,PROXY
      - MATCH,DIRECT

    proxy-groups:
      - name: "PROXY"
        type: select
        interval: 3000
        proxies:
          - "hk-01"
          - "DIRECT"

    rule-providers:
      reject:
        type: file
        behavior: domain
        path: /ruleset/reject.yaml

      icloud:
        type: file
        behavior: domain
        path: /ruleset/icloud.yaml

      apple:
        type: file 
        behavior: domain
        path: /ruleset/apple.yaml

      google:
        type: file
        behavior: domain
        path: /ruleset/google.yaml

      proxy:
        type: file
        behavior: domain
        path: /ruleset/proxy.yaml

      direct:
        type: file
        behavior: domain
        path: /ruleset/direct.yaml

      private:
        type: file
        behavior: domain
        path: /ruleset/private.yaml

      gfw:
        type: file
        behavior: domain
        path: /ruleset/gfw.yaml

      tld-not-cn:
        type: file
        behavior: domain
        path: /ruleset/tld-not-cn.yaml

      telegramcidr:
        type: file
        behavior: ipcidr
        path: /ruleset/telegramcidr.yaml

      cncidr:
        type: file
        behavior: ipcidr
        path: /ruleset/cncidr.yaml

      lancidr:
        type: file
        behavior: ipcidr
        path: /ruleset/lancidr.yaml

      applications:
        type: file
        behavior: classical
        path: /ruleset/applications.yaml
