# rsshub-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: rsshub-service
  namespace: rss
spec:
  type: NodePort
  selector:
    app: rsshub
  ports:
    - protocol: TCP
      port: 1200
      targetPort: 1200
      nodePort: 31200
