# rsshub-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsshub
  namespace: rss
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rsshub
  template:
    metadata:
      labels:
        app: rsshub
    spec:
      containers:
        - name: rsshub
          image: diygod/rsshub:chromium-bundled
          envFrom:
            - configMapRef:
                name: rsshub-config
          env:
            - name: http_proxy
              value: "http://clash-service:7890"
            - name: https_proxy
              value: "http://clash-service:7890"
            - name: no_proxy
              value: "localhost,127.0.0.1,.svc.cluster.local"
          ports:
            - containerPort: 1200
          livenessProbe:
            httpGet:
              path: /healthz
              port: 1200
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /healthz
              port: 1200
            initialDelaySeconds: 10
            periodSeconds: 30
