# rsshub-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsshub
  namespace: rss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rsshub
  template:
    metadata:
      labels:
        app: rsshub
    spec:
      containers:
        - name: rsshub
          image: diygod/rsshub:chromium-bundled
          envFrom:
            - configMapRef:
                name: rsshub-config
          ports:
            - containerPort: 1200
          livenessProbe:
            httpGet:
              path: /healthz
              port: 1200
            initialDelaySeconds: 20
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /healthz
              port: 1200
            initialDelaySeconds: 10
            periodSeconds: 30
